# Generated by Django 5.0.3 on 2024-10-08 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author_category_image_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='muallif',
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.author'),
            preserve_default=False,
        ),
    ]
